import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "adepejuStephen",
      email: "admin@example.com",
      password: bcrypt.hashSync("Stephen"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("Stephen"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Air Force 1 React ",
      desc: "From hoops staple to urban street legend,the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Now you can stand out to fit in.",
      color: "White/Light Photo Blue/Deep Royal Blue/White",
      category: "Sneekers",
      status: "Trending",
      slug: "nike-air-force-1-react",
      image: [
        "/images/products/airforceWhite/img01.png",
        "/images/products/airforceWhite/img02.png",
        "/images/products/airforceWhite/img03.png",
        "/images/products/airforceWhite/img04.png",
        "/images/products/airforceWhite/img05.png",
      ],
      price: 100,
      rating: 4.5,
      numReviews: 5,
      countInStcock: 20,
    },

    {
      name: "Nike ACG Air Deschutz + ",
      desc: " From city hikes to canyon trails and long walks on the beach, the Nike ACG Air Deschutz + is built to feel comfortable.It's got a classic '90s look and rugged outdoor-inspired design, with plush padding around the ankle for support.A heavy-duty webbing strap and adjustable hook-and-loop closure keep you focused on the journey ahead.",
      color: "Moon Fossil/Black",
      category: "Sandals",
      status: "New Products",
      slug: "nike-acg-air-deschutz",
      image: [
        "/images/products/acgMoon/img01.png",
        "/images/products/acgMoon/img02.png",
        "/images/products/acgMoon/img03.png",
        "/images/products/acgMoon/img04.png",
      ],
      price: 110,
      rating: 4.7,
      numReviews: 6,
      countInStcock: 20,
    },

    {
      name: "Nike Air Force 1 React black",
      desc: "From hoops staple to urban street legend,the Nike AF-1 React takes another step forward into shoe iconography. Amplified features from the outsole to the branding add dramatic expression to the storied look while Nike React tech assists with a smooth ride. Now you can stand out to fit in.",
      color: "Black/Team Orange/Pink Prime/Black",
      category: "Sneekers",
      status: "New Products",
      slug: "nike-air-force-1-react-black",
      image: [
        "/images/products/airforceBlack/img01.png",
        "/images/products/airforceBlack/img02.png",
        "/images/products/airforceBlack/img03.png",
        "/images/products/airforceBlack/img04.png",
        "/images/products/airforceBlack/img05.png",
      ],
      price: 100,
      rating: 4.5,
      numReviews: 5,
      countInStcock: 20,
    },

    {
      name: "TERREX CYPREX ULTRA II DLX SANDALS ",
      desc: " From city hikes to canyon trails and long walks on the beach, the Nike ACG Air Deschutz + is built to feel comfortable.It's got a classic '90s look and rugged outdoor-inspired design, with plush padding around the ankle for support.A heavy-duty webbing strap and adjustable hook-and-loop closure keep you focused on the journey ahead.",
      color: "Wonder White/Pulse Lime/Crystal White",
      category: "Sandals",
      status: "Trending",
      slug: "terrex-cyprex-ultra-ii-dlx-sandals",
      image: [
        "/images/products/terrexSandals/img01.png",
        "/images/products/terrexSandalse/img02.png",
        "/images/products/terrexSandals/img03.png",
        "/images/products/terrexSandals/img04.png",
      ],
      price: 120,
      rating: 4.5,
      numReviews: 5,
      countInStcock: 18,
    },

    {
      name: "Jordan Point Lane",
      desc: "The Jordan Point Lane mixes elements from game shoes MJ wore during 3 of his most memorable seasons.Named after his Chicago address, this mash-up pulls in bits and pieces from the AJ3, AJ6 and AJ11 to create a shoe that's inspired by greatness and uncompromising in its comfort.",
      color: "Pure Platinum/White/Wolf Grey",
      category: "Sneekers",
      status: "Trending",
      slug: "jordan-point-lane",
      image: [
        "/images/products/jordanPointWhite/img01.png",
        "/images/products/jordanPointWhite/img02.png",
        "/images/products/jordanPointWhite/img03.png",
        "/images/products/jordanPointWhite/img04.png",
        "/images/products/jordanPointWhite/img05.png",
      ],
      price: 150,
      rating: 4.5,
      numReviews: 5,
      countInStcock: 20,
    },
    {
      name: "Nike Air Deschutz BeTrue",
      desc: "The Nike Air Deschutz BeTrue returns with its classic '90s style and outdoor-inspired design.Celebrating the LGBTQIA+ community, its glitter-finished black straps have a spirited-but-rugged look while the plush padding features subtle pops of Pride colours.The removable pouch with embroidered flag snaps on and off from the heel, letting you stash your stuff.",
      color: "Multi-Colour/Black",
      category: "Sandals",
      status: "New Products",
      slug: "nike-air-deschutz-betrue",
      image: [
        "/images/products/nikeBeTrue/img01.png",
        "/images/products/nikeBeTrue/img02.png",
        "/images/products/nikeBeTrue/img03.png",
        "/images/products/nikeBeTrue/img04.png",
        "/images/products/nikeBeTrue/img05.png",
      ],
      price: 170,
      rating: 4.5,
      numReviews: 5,
      countInStcock: 20,
    },
    {
      name: "ADILETTE AQUA SLIDES",
      desc: "Rinse off after the pool in these shower-friendly sandals. Keeping it simple, the smooth slip-ons reveal their adidas DNA with signature 3-Stripes. Soft cushioning rewards tired feet with plush comfort.",
      color: "Solar Red",
      category: "Slides",
      status: "Trending",
      slug: "adilette-aqua-slides",
      image: [
        "/images/products/adiletteAqua/img01.png",
        "/images/products/adiletteAqua/img02.png",
        "/images/products/adiletteAqua/img03.png",
        "/images/products/adiletteAqua/img04.png",
        "/images/products/adiletteAqua/img05.png",
      ],
      price: 40,
      rating: 4.5,
      numReviews: 5,
      countInStcock: 20,
    },
    {
      name: "Classic Lined Tie-Dye Clog",
      desc: "Timeless, fun and full of peaceful good vibes, the bright pops of tie-dye graphics on these clogs are the perfect way to make a groovy style statement on the go or while you’re just hangin’ out. Snuggle-ready linings are sure to inspire warm and fuzzy feelings when the temperatures drop. Grounded in comfort, spiked with personality for all ages. From downtime to downtown, these are ready to rock wherever you choose to roll.",
      color: "multi/Black",
      category: "Clogs",
      status: "Trending",
      slug: "classic-lined-tie-dye-clog",
      image: [
        "/images/products/dyedClog/img01.png",
        "/images/products/dyedClog/img02.png",
        "/images/products/dyedClog/img03.png",
        "/images/products/dyedClog/img04.png",
        "/images/products/dyedClog/img05.png",
      ],
      price: 42,
      rating: 4.2,
      numReviews: 5,
      countInStcock: 20,
    },
    {
      name: "ADILETTE COMFORT SLIDES",
      desc: "Whether you're heading to the locker room after an intense gym session or at home recovering on the couch, these slides keep your feet wrapped in lightweight comfort. Pair them with socks and shorts for your post-workout look or with your favourite swimwear for the ultimate beach vibe. The adidas 3-Stripes design completes your sport style.",
      color: "Core Black",
      category: "Slides",
      status: "New Products",
      slug: "adilette-comfort-slides",
      image: [
        "/images/products/adiletteComfort/img01.png",
        "/images/products/adiletteComfort/img02.png",
        "/images/products/adiletteComfort/img03.png",
        "/images/products/adiletteComfort/img04.png",
        "/images/products/adiletteComfort/img05.png",
      ],
      price: 42,
      rating: 4.0,
      numReviews: 5,
      countInStcock: 20,
    },
    {
      name: "CLASSIC LINED CLOG",
      desc: "Everybody loves the comfort of the Crocs Classic Clog — and now there’s a toasty lined version to keep the feeling going all season. The soft, fuzzy liner adds to the cushion and comfort, indoors or out. Great as a slipper, yet capable to run errands, too. Croslite™ foam construction keeps them light and easy to wear. The pivoting heel strap gives you a secure fit, or push it forward to just step in and go.",
      color: "Black",
      category: "Clogs",
      status: "New Products",
      slug: "classic-lined-clog",
      image: [
        "/images/products/classicClog/img01.png",
        "/images/products/classicClog/img02.png",
        "/images/products/classicClog/img03.png",
        "/images/products/classicClog/img04.png",
        "/images/productsclassicClog/img05.png",
      ],
      price: 55,
      rating: 4.5,
      numReviews: 5,
      countInStcock: 20,
    },
    {
      name: "RACER TR SLIDES",
      desc: "Introduced in 1972, the beloved adidas Adilette slides have been much copied but never surpassed. Designed to transition seamlessly from the beach to the locker room to running errands around town, this version has a soft EVA bandage upper and a comfortable contoured footbed.",
      color: "Royal Blue",
      category: "Slides",
      status: "Trending",
      slug: "racer-tr-slides",
      image: [
        "/images/products/racerTr/img01.png",
        "/images/products/racerTr/img02.png",
        "/images/products/racerTr/img03.png",
        "/images/products/racerTr/img04.png",
        "/images/products/racerTr/img05.png",
      ],
      price: 60,
      rating: 4.1,
      numReviews: 5,
      countInStcock: 20,
    },
    {
      name: "CLASSIC LINED MARBLED CLOG",
      desc: "Everybody loves the comfort of the Crocs Classic Clog — and now there’s a toasty lined version to keep the feeling going all season. The soft, fuzzy liner adds to the cushion and comfort, indoors or out. Great as a slipper, yet capable to run errands, too. Croslite™ foam construction keeps them light and easy to wear. This special pair features a new marbled Croslite™ treatment that creates a colorful swirled effect that is completely unique, just like you!",
      color: "White/Black",
      category: "Clogs",
      status: "New Products",
      slug: "classic-lined-marbled-clog",
      image: [
        "/images/products/mableClog/img01.png",
        "/images/products/mableClog/img02.png",
        "/images/products/mableClog/img03.png",
        "/images/products/mableClog/img04.png",
        "/images/products/mableClog/img05.png",
      ],
      price: 68,
      rating: 4.5,
      numReviews: 3,
      countInStcock: 20,
    },
  ],
};

export default data;
