import Head from "next/head";
import Image from "next/image";
import { Fragment } from "react";
import styles from "../styles/Home.module.css";
import data from "../utils/data";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.products.map((product, id) => (
          <Image height={200} width= {200} src={product.image[0]} key={id} alt={product.name}/>
        ))}
      </main>
    </div>
  );
}
